baseURL = 'https://mudrk.github.io/'
languageCode = 'ja-jp'
title = 'チラシの裏'
theme = "etch"

enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = ""
  copyright = "Copyright © 2022 mudrk"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
